config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # resources :users do
  #   resources :purchases, only: [:index, :create]
  #   resources :products, only: [:new, :create, :index]
  # end

  resources :products do
    resources :purchases, only: [:index, :new, :create]
    collection do
      get 'search'
      get "index_accessories"
      get "index_promo"
    end
  end
  resources :purchases, only: [:show]
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user

  has_many :purchases
  validates :product_type, presence: true, length: { minimum: 3 }
  validates :name, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 20 }
  validates :region, :roast_type, presence: true, length: { minimum: 4 }
  validates :weight, :price, presence: true
  has_one_attached :photo
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :user, presence: true
  validates :product, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :company_name, :register_number, presence: true
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :is_company, :company_name, :register_number, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :is_company, :company_name, :register_number, :photo])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @products = Product.where(user: current_user)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action: set_product, only:
  skip_before_action :authenticate_user!, only: [ :index, :index_accessories, :index_promo, :show ]

  def index
    @coffees = Product.where(product_type: "Coffee")
    @pagy, @coffees = pagy @coffees, items: params.fetch(:count, 12)
  end

  def index_accessories
    @accessories = Product.where.not(product_type: "Coffee")
    @pagy, @accessories = pagy @accessories, items: params.fetch(:count, 12)
  end

  def index_promo
    @promos = Product.where(is_promo: true)
    @pagy, @promos = pagy @promos, items: params.fetch(:count, 12)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to @product, notice: "Product created succesfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path, notice: 'Bookmark was successfully removed.', status: :see_other
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to product_path(@product)
  end

  def search
    @search_results = Product.where("name ILIKE ?", "%#{params[:search][:query]}%")
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :region, :roast_type, :description, :weight, :price, :product_type, :is_promo, :photo)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!

  def new
    @product = Product.find(params[:product_id])
    @purchase = Purchase.new
  end

  def show
    @purchase_item = Purchase.find(params[:id])
    # @purchase = current_user.purchases.build(product_item: @purchase_item)
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @product = Product.find(params[:product_id])
    @purchase.product = @product
    @purchase.user = current_user
    if @purchase.save
      # render :confirmation
      redirect_to @purchase, notice: "Product was succesfully purchased"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def purchase_params
    params.require(:purchase).permit(:address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeBreak</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,200;0,400;1,200&family=Instrument+Sans&family=Racing+Sans+One&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="container-macro">
    <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/_accessories.html.erb
<%# <div class="container"> %>
  <div class="row">
    <div class="col-6">
      <%= image_tag asset_path('accessory.jpg'), alt: 'Coffee Image', class: 'img-fluid' %>
    </div>
    <div class="col-6">
      <div class="content">
        <h2>Accessories</h2>
        <p>Elevating Your Coffee Experience.
        In the world of coffee, the journey from bean to cup is a fascinating one, and coffee accessories play a crucial role in enhancing that journey.
        From the humble grinder that transforms whole beans into a perfect grind to the precision of the pour-over kettle, these tools are the unsung heroes of your daily brew.</p>
        <%= link_to "Learn More", index_accessories_products_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

<%# </div> %>

app/views/pages/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('home_banner.jpg') %>);">
  <div class="container">
    <h1>Welcome to our flavor heaven! We're thrilled to have you here, exploring the incredible world of coffee with us. On our website, you'll find a carefully curated selection of the finest coffee beans, roasted with passion and dedication to bring you the most authentic and delightful experience</h1>
    <br>
    <p>Special coffes and roasted beans from our best producers from all Brazil.</p>
  </div>
</div>

app/views/pages/_banner_business.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('home_banner.jpg') %>);">
  <div class="container">
    <h1>Anuncie seus produtos no maior MarketPlace de cafe especial do Brasil!</h1>
    <br>
  </div>
</div>

app/views/pages/_coffee.html.erb
<%# <div class="container"> %>
  <div class="row">
    <div class="col-6">
      <div class="content">
        <h2>Coffee</h2>
        <p>More than just a morning ritual, it's a daily dose of inspiration.
        This beloved brew not only wakes you up but also ignites your senses, fueling your day with creativity and clarity.
        With each sip, you're transported to a world where ideas flow, conversations spark, and productivity soars.
        Coffee isn't just a beverage; it's a companion in your journey, offering comfort, warmth, and a little kick of motivation.
        So, whether you're sipping it alone or sharing it with friends, embrace the goodness of coffee and let it be your trusted ally in the quest for a better day.</p>
        <%= link_to "Learn More", products_path, class: "btn btn-primary" %>
      </div>
    </div>
    <div class="col-6">
      <%= image_tag asset_path('coffee_image.jpg'), alt: 'Coffee Image', class: 'img-fluid' %>
    </div>
  </div>
<%# </div> %>

app/views/pages/_promo.html.erb
<%# <div class="promo-section"> %>
  <div class="text-center mb-3">
    <h2 class ="h2-special" style="margin-bottom: 50px;">Promo</h2>
  </div>

  <div id="carouselExample" class="carousel slide">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag 'accessory.jpg', class: 'img-carrousel' %>
      </div>
      <div class="carousel-item">
        <%= image_tag 'coffee_image.jpg', class: 'img-carrousel' %>
      </div>
      <div class="carousel-item">
      <%= image_tag 'placeholder.jpg', class: 'img-carrousel' %>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div class="text-center mb-3 mt-3">
    <p>Hey! Check out our exclusive sales! Don't miss out on your passport to extraordinary flavors and savings.</p>
  </div>
  <div class="btn-content">
    <%= link_to "Learn More", index_promo_products_path, class: "btn btn-primary btn-home" %>
  </div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? && current_user.is_company? %>
<%= render "pages/banner_business" %>
<br>
<h1>My products:</h1>

<div class="cards">

  <% @products.each do |product| %>
    <div class="card-product">
      <% if product.photo.key? %>
      <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill %>
      <% else %>
      <%= image_tag "placeholder.jpg", class: "product_image" %>
      <% end %>
      <div class="product-info">
        <h2><%= product.name %></h2>
        <p> US$ <%= product.price %>.00</p>
        <p>Grain type: <%= product.roast_type %></p>
        <div class="product-weight">
          <p><%= product.weight %> grams</p>
          <%= link_to "View Details", product_path(product), class: "btn btn-primary" %>
          <%= link_to "Edit Product", edit_product_path(product), class: "btn btn-primary" %>
          <%= link_to "Delete", product_path(product), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<h1>Add new product:</h1>
<%= link_to "Add new product", new_product_path, class: "btn btn-primary" %>



<% else %>
  <%= render "pages/banner" %>
  <br>
  <p>Browse through our categories and discover a variety of premium coffees, from smooth and aromatic to bold and full-bodied. We also offer essential accessories to perfect your coffee cup, from grinders to specialized brewing methods.</p>
  <p>Our commitment is to provide you with an exceptional coffee journey, from the moment you choose your beans to the first steaming cup you savor. Whether you're a seasoned coffee lover or just beginning to explore this wonderful world, we're here to serve you.

Feel free to explore our website, make your selections, and if you have any questions or need guidance, our team is ready to assist. Enjoy your visit and dive into the pleasure of coffee!"

I hope this message helps you welcome your visitors with enthusiasm and invites them to explore your coffee products.</p>

  <br>
  <hr style="width:50%; margin: auto; margin-top:15px; margin-bottom:65px;">
  <%= render "pages/coffee" %>
  <br>
  <hr style="width:50%; margin: auto; margin-top:50px; margin-bottom:65px;">
  <%= render "pages/accessories" %>
  <br>
  <hr style="width:50%; margin: auto; margin-top:50px; margin-bottom:65px;">
  <%= render "pages/promo" %>
<% end %>
</div>

app/views/products/_form.html.erb
<%= simple_form_for([ @user, @product ]) do |f| %>

  <%= f.input :name %>

  <%= f.input :product_type, collection: ["Coffee", "filter", "grinder", "cup"] %>

  <%= f.input :description %>

  <%= f.input :region %>

  <%= f.input :roast_type, collection: ['grain', 'coarse', 'thin'] %>

  <%= f.input :weight, collection: ["250g", "500g", "1000g"] %>

  <%= f.input :price %>

  <%= f.input :is_promo, required: true %>

  <%= f.input :photo, as: :file %>

  <div class="d-grid">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container mt-5">
  <h1>Edit product</h1>

  <div class="card">
    <div class="card-body">
      <%= render 'form', user: current_user, product: @product %>

      <%= link_to 'Back to yours products', root_path, class: "btn btn-secondary mt-3" %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path('background.jpg') %>)">
  Special Coffees
</div>

<div class="cards">

  <% @coffees.each do |coffee| %>
    <div class="card-product">
      <% if coffee.photo.key? %>
        <%= cl_image_tag coffee.photo.key, height: 300, width: 400, crop: :fill %>
      <% else %>
        <%= image_tag "placeholder.jpg", class: "product_image" %>
      <% end %>
      <div class="product-info">
        <h2><%= coffee.name %></h2>
        <p> US$ <%= coffee.price %>.00</p>
        <p>Grain type: <%= coffee.roast_type %></p>
        <div class="product-weight">
          <p><%= coffee.weight %> grams</p>
          <%= link_to "View Details", product_path(coffee), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="d-flex justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/products/index_accessories.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path('background.jpg') %>)">
  Accessories
</div>

<div class="cards">

  <% @accessories.each do |accessory| %>
    <div class="card-product">
      <% if accessory.photo.key? %>
        <%= cl_image_tag accessory.photo.key, height: 300, width: 400, crop: :fill %>
      <% else %>
        <%= image_tag "accessory.jpg", class: "accessory_image" %>
      <% end %>
      <div class="product-info">
        <h2><%= accessory.name %></h2>
        <p> US$ <%= accessory.price %>.00</p>
        <p>Product type: <%= accessory.product_type %></p>
          <div class="details">
            <%= link_to "View Details", product_path(accessory), class: "btn btn-primary" %>
          </div>
      </div>
    </div>
  <% end %>
</div>
<div class="d-flex justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/products/index_promo.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path('background.jpg') %>)">
  On sale NOW!
</div>

<div class="cards">

  <% @promos.each do |promo| %>
    <div class="card-product">
    <% if promo.photo.key? %>
      <%= cl_image_tag promo.photo.key, height: 300, width: 400, crop: :fill %>
    <% elsif promo.product_type == "Coffee" %>
      <%= image_tag "placeholder.jpg", class: "product_image" %>
    <% else %>
      <%= image_tag "accessory.jpg", class: "accessory_image" %>
    <% end %>
      <div class="accessory-info">
        <h2><%= promo.name %></h2>
        <p> US$ <%= promo.price %>.00</p>
        <p>Product type: <%= promo.product_type %></p>
        <div class="details">
          <%= link_to "View Details", product_path(promo), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="d-flex justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/products/new.html.erb
<div class="container">
<h1>Create a new product</h1>
<%= render "form", product: @product %>
</div>

app/views/products/search.html.erb
<br>

<h1>Search Results</h1>

<% if @search_results.any? %>
  <ul>
    <% @search_results.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No results found.</p>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p><%= @product.description %></p>
<%= link_to 'Purchase', new_product_purchase_path(@product), class: 'btn btn-primary' %>


<%if @product.product_type == "Coffee" %>
  <div class="card-product" >
    <% if @product.photo.key? %>
      <%= cl_image_tag @product.photo.key, height: 300, width: 400, crop: :fill %>
    <% else %>
      <%= image_tag "placeholder.jpg", class: "product_image" %>
    <% end %>
    <div class="product-details">
      <p><strong>Name:</strong> <%= @product.name %> </p>
      <p><strong>Details:</strong> <%= @product.description %> </p>
      <p><strong>Roast Type:</strong> <%= @product.roast_type %> </p>
      <p><strong>Net weight:</strong> <%= @product.weight %> </p>
      <p><strong>Price: $ </strong> <%= @product.price %>
    </div>
  </div>

    <% if current_user && current_user.is_company?  %>
      <p class="btn btn-primary"><%= link_to 'back to my products', root_path %></p>
    <% elsif @product.is_promo%>
      <p class="btn btn-primary"><%= link_to 'back to Promos', index_promo_products_path %></p>
    <% else %>
      <p class="btn btn-primary"><%= link_to 'back to Coffee', products_path %></p>
    <% end %>

<% else %>

  <div class="card-product" >
    <% if @product.photo.key? %>
      <%= cl_image_tag @product.photo.key, height: 300, width: 400, crop: :fill %>
    <% else %>
      <%= image_tag "placeholder.jpg", class: "product_image" %>
    <% end %>
    <div class="product-details">
      <p><strong>Name:</strong> <%= @product.name %> </p>
      <p><strong>Product Type:</strong> <%= @product.product_type %> </p>
      <p><strong>Details:</strong> <%= @product.description %> </p>
      <p><strong>Price: $ </strong> <%= @product.price %>
      <%# <%= link_to "#" do%>
        <%# <i></i> procurar icone de "checkout" no font awesome  %>
    </div>
  </div>



     <% if current_user && current_user.is_company?  %>
      <p class="btn btn-primary"><%= link_to 'back to my products', root_path %></p>
    <% elsif @product.is_promo%>
    <div class="d-flex">
      <p class="btn btn-primary"><%= link_to 'back to Promos', index_promo_products_path %></p>
      <p class="btn btn-primary"><%= link_to 'back to Accessories', index_accessories_products_path %></p>
    </div>
    <% else %>
      <p class="btn btn-primary"><%= link_to 'back to Accessories', index_accessories_products_path %></p>
    <% end %>

<% end %>

<%# index_promo_products %>

app/views/purchases/_form.html.erb
<%= simple_form_for([ product, purchase ]) do |f| %>

  <%= f.input :address %>
  <div class="d-grid">
    <%= f.submit "Confirm your purchase", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/purchases/new.html.erb
<div class="container">
<h1>Confirm your purchase</h1>
<p>Name: <%= current_user.first_name %></p>
<p>Last name: <%= current_user.last_name %></p>
<%= link_to "cancel purchase", product_path(@product) %>
<%= render "form", product: @product, purchase: @purchase %>
</div>

app/views/purchases/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path('background.jpg') %>)">
  Confirmation
</div>

  <div class="card-product" >
    <%= image_tag "placeholder.jpg", class: "coffee_image" %>
    <div class="product-details">
      <h2>Congratulations</h2>
      <p>Your <%= @purchase_item.product.name %> was successfully purchased!</p>
    </div>
  </div>

  <p class="btn btn-primary"><%= link_to 'back to Home', root_path %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/OSuricato/coffee-break"><i class="fab fa-github"></i> View on GitHub </a>
 </div>
  <div>
    <i class="fa-solid fa-mug-hot fa-lg"></i>
  </div>
  <div class="footer-copyright">
    Coffe Break <i class="fa-regular fa-copyright"></i> 2023
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="container fixed-top mt-3">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand px-3" do %>
        <i class="fa-solid fa-mug-hot fa-lg"></i>
        <span class="ml-2 px-2">Coffee Break</span>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
          <% if user_signed_in? %>
      <div class="collapse navbar-collapse mx-3" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
            <%# end of search bar %>
            <% if current_user.is_company? %>
              <li class="nav-item">
                <%= link_to "My Products", root_path, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Coffees", products_path, class: "nav-link" %>
              </li>
              <li class="nav-item active">
                <%= link_to "Accessories", index_accessories_products_path, class: "nav-link" %>
              </li>
              <li class="nav-item active">
                <%= link_to "Promos", index_promo_products_path, class: "nav-link" %>
              </li>
            <% end %>
                <span class="nav-item active">
              <form novalidate="novalidate" class="simple_form search " action="<%= search_products_path %>" accept-charset="UTF-8" method="get">
                <div class="search-form-control form-group d-flex">
                  <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Search" />
                  <button name="button" type="submit" class="btn btn-flat ">
                    <i class="fa-solid fa-magnifying-glass" style="color: #f2f2f2;"></i>
                  </button>
                </div>
              </form>
            </span>
            <li class="nav-item dropdown">
              <% if current_user.photo.key? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", width: 40, height: 40, crop: "fill", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= image_tag "meerkat.webp", class: "avatar dropdown-toggle py-1", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Manage your account", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </form>
          </li>
          <%# end of search bar %>
          <% else %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
            <%# end of search bar %>

            <li class="nav-item">
              <%= link_to "Coffees", products_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Accessories", index_accessories_products_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Promos", index_promo_products_path, class: "nav-link" %>
            </li>
                <span class="nav-item active">
              <form novalidate="novalidate" class="simple_form search " action="<%= search_products_path %>" accept-charset="UTF-8" method="get">
                <div class="search-form-control form-group d-flex">
                  <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Search" />
                  <button name="button" type="submit" class="btn btn-flat ">
                    <i class="fa-solid fa-magnifying-glass" style="color: #f2f2f2;"></i>
                  </button>
                  <li class="nav-item">
                    <%= link_to new_user_session_path, class: "nav-link" do %>
                      <i class="fa-solid fa-user"></i>
                    <% end %>
          <% end %>
                  </li>
                </div>
              </form>
            </span>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar_test.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo_colored.png" %>
      <span class="ml-2">Coffee Break</span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <% if user_signed_in? %>
          <li class="nav-item active">
            <form novalidate="novalidate" class="simple_form search" action="<%= search_products_path %>" accept-charset="UTF-8" method="get">
              <div class="search-form-control form-group d-flex">
                <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Search" />
                <button name="button" type="submit" class="btn btn-flat">
                  <i class="fas fa-search nav-link"></i>
                </button>
              </div>
            </form>
          </li>
          <%# end of search bar %>
          <% if current_user.is_company? %>
            <li class="nav-item">
              <%= link_to "My Products", root_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Coffees", products_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Accessories", index_accessories_products_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <% if current_user.photo.key? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "meerkat.webp", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Manage your account", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>